apiVersion: v1
kind: Service
metadata:
  name: blerter-vaadin
spec:
  type: NodePort
  ports:
    - name: token-server
      port: 4030
      protocol: TCP
      targetPort: 4030
  selector:
    name:  blerter-vaadin
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: blerter-vaadin
spec:
  replicas: 1
  template:
    metadata:
      name:  blerter-vaadin
      labels:
        name:  blerter-vaadin
        app:  blerter-vaadin
    spec:
      containers:
        - name:  blerter-vaadin
          image: sirwhitemonkey/blerter-vaadin
          #resources:
          #  requests:
          #    memory: "1Gi"
          #  limits:
          #    memory: "1Gi"
          env:
            - name: BLERTER_SERVICE_HOST
              value: BLERTER_SERVICE_HOST
            - name: BLERTER_SERVICE_PORT
              value: "4002"
          ports:
            - containerPort: 4030
   